service: telemetricdataprod
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'
